[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "valladopy"
version = "0.4.1"
description = "Routines from Fundamentals of Astrodynamics and Applications by David Vallado"
readme = { file = "PYPI_DESCRIPTION.md", content-type = "text/markdown" }
authors = [{name = "David Vallado", email = "davallado@gmail.com"}]
license = {text = "AGPL-3.0"}
dependencies = [
    "numpy<3.0",
    "pydantic<3.0",
    "scipy>=1.15,<2.0",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Topic :: Scientific/Engineering",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13"
]

[tool.black]
target-version = ['py311', 'py312', 'py313']
